include(acmake_common)
include(acmake_mysql_support)

# usage: acmake_mysqlpp_support(<target>)
macro(acmake_mysqlpp_support TARGET)
    acmake_mysql_support(${TARGET})
    find_package(MySqlpp REQUIRED)
    include_directories(${MYSQLPP_INCLUDE_DIRS})
    target_link_libraries(${TARGET} ${MYSQLPP_LIBRARIES})
endmacro()
