# usage: acmake_assert(<variable> [<message>])
macro(acmake_assert)
    acmake_assert_defined(${ARGN})
    if(${ARGC} GREATER 0)
        if(NOT ${ARGV0})
            if(${ARGC} GREATER 1)
                message(FATAL_ERROR "Assert failed: ${ARGV0}\n${ARGV1}")
            else()
                message(FATAL_ERROR "Assert failed: ${ARGV0}")
            endif()
        endif()
    endif()
endmacro()

# usage: acmake_assert_defined(<variable> [<message>])
macro(acmake_assert_defined)
    if(${ARGC} GREATER 0)
        if(NOT DEFINED ${ARGV0})
            if(${ARGC} GREATER 1)
                message(FATAL_ERROR "Assert failed: ${ARGV0}\n${ARGV1}")
            else()
                message(FATAL_ERROR "Assert failed: ${ARGV0}")
            endif()
        endif()
    endif()
endmacro()
