include(ans.boost_support)
include(ans.ans_support)
include(ans.cml_support)
include(ans.cmlex_support)
include(ans.qt_support)
include(ans.opencv_support)
include(ans.qwt_support)
include(ans.create_vcproj_userfile)
include(ans.disable_msvc_warnings)
include(ans.list_subdirectories)
include(ans.set_output_dir)
include(ans.source_group_by_dir)
# bring from OGRE
include(FindPkgMacros)
