FIND_PATH(OPENGL_INCLUDE_DIR glew.h
	"${dep}\\include\\GL\\"
)

FIND_LIBRARY(OPENGL0_LIBRARY 
 NAMES
    glew32
 PATHS
	"${dep}\\lib\\${PLATFORM_NAME}_${BRT_NAME}\\"
)

FIND_LIBRARY(OPENGL1_LIBRARY 
 NAMES
	glut32	
 PATHS
	"${dep}\\lib\\${PLATFORM_NAME}_${BRT_NAME}\\"
)

IF (OPENGL_INCLUDE_DIR AND OPENGL0_LIBRARY AND OPENGL1_LIBRARY)
    SET(TERMCAP_FOUND TRUE)
	message( ${ASTATUS} "Found OpenGL headers     : ${OPENGL_INCLUDE_DIR}")
	message( ${ASTATUS} "Found OpenGL library     : ${OPENGL0_LIBRARY}")
    INCLUDE_DIRECTORIES(${OPENGL_INCLUDE_DIR})
ELSE (OPENGL_INCLUDE_DIR AND OPENGL0_LIBRARY AND OPENGL1_LIBRARY)
    SET(TERMCAP_FOUND FALSE)
ENDIF (OPENGL_INCLUDE_DIR AND OPENGL0_LIBRARY AND OPENGL1_LIBRARY)
