#ifndef __PP_SEQ_FOREACH_H__
#define __PP_SEQ_FOREACH_H__

#include <standard\Preprocessor\pp_basic.h>

// A "typical" mapping macro. PP_SEQ_FOR_EACH(macro, a, b, c, ...) expands to
// macro(a) macro(b) macro(c) ...
// The helper macro COUNT(a, b, c, ...) expands to the number of
// arguments, and IDENTITY(x) is needed to control the order of
// expansion of __VA_ARGS__ on Visual C++ compilers.
#define PP_SEQ_FOR_EACH(macro, data, seqvence_start, ...) \
    IDENTITY( \
        APPLY(PP_CHOOSE_ENUM_SEQ_START, PP_VARADICAL_ENUM_COUNT_EXPAND(__VA_ARGS__)) \
            (macro, data, seqvence_start, __VA_ARGS__))

// MACRO SWIPE WORKAROUND :///
#define PP_SEQ_FOR_EACH_I(macro, data, seqvence_start, ...) \
    IDENTITY( \
        APPLY(PP_CHOOSE_ENUM_SEQ_I_START, PP_VARADICAL_ENUM_COUNT_EXPAND(__VA_ARGS__)) \
            (macro, data, seqvence_start, __VA_ARGS__))

#define PP_CHOOSE_ENUM_SEQ_START(count) PP_ENUM_SEQ_ ## count
#define PP_CHOOSE_ENUM_SEQ_I_START(count) PP_ENUM_SEQ_I_ ## count

#define APPLY(macro, ...) IDENTITY(macro(__VA_ARGS__))

#define PP_CONCAT_II(L, M0, M1, R) L ## M0 ## M1 ## R
#define PP_CONCAT_I(L, M, R) L ## M ## R
#define PP_CONCAT(L, R) L ## R

#define PP_ENUM_SEQ_1(m,  data, s, x)      m(data, 0, s, x)
#define PP_ENUM_SEQ_2(m,  data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_1 (m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_3(m,  data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_2 (m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_4(m,  data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_3 (m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_5(m,  data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_4 (m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_6(m,  data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_5 (m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_7(m,  data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_6 (m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_8(m,  data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_7 (m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_9(m,  data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_8 (m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_10(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_9 (m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_11(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_10(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_12(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_11(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_13(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_12(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_14(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_13(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_15(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_14(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_16(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_15(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_17(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_16(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_18(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_17(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_19(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_18(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_20(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_19(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_21(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_20(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_22(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_21(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_23(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_22(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_24(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_23(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_25(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_24(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_26(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_25(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_27(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_26(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_28(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_27(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_29(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_28(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_30(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_29(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_31(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_30(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_32(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_31(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_33(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_32(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_34(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_33(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_35(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_34(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_36(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_35(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_37(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_36(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_38(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_37(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_39(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_38(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_40(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_39(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_41(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_40(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_42(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_41(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_43(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_42(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_44(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_43(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_45(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_44(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_46(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_45(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_47(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_46(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_48(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_47(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_49(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_48(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_50(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_49(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_51(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_50(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_52(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_51(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_53(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_52(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_54(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_53(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_55(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_54(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_56(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_55(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_57(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_56(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_58(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_57(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_59(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_58(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_60(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_59(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_61(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_60(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_62(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_61(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_63(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_62(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_64(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_63(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_65(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_64(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_66(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_65(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_67(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_66(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_68(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_67(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_69(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_68(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_70(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_69(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_71(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_70(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_72(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_71(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_73(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_72(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_74(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_73(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_75(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_74(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_76(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_75(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_77(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_76(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_78(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_77(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_79(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_78(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_80(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_79(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_81(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_80(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_82(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_81(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_83(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_82(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_84(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_83(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_85(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_84(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_86(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_85(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_87(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_86(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_88(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_87(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_89(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_88(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_90(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_89(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_91(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_90(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_92(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_91(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_93(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_92(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_94(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_93(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_95(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_94(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_96(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_95(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_97(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_96(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_98(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_97(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_99(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_98(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_100(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_99(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_101(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_100(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_102(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_101(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_103(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_102(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_104(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_103(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_105(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_104(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_106(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_105(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_107(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_106(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_108(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_107(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_109(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_108(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_110(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_109(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_111(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_110(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_112(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_111(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_113(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_112(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_114(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_113(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_115(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_114(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_116(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_115(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_117(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_116(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_118(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_117(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_119(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_118(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_120(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_119(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_121(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_120(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_122(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_121(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_123(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_122(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_124(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_123(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_125(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_124(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_126(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_125(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_127(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_126(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_128(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_127(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_129(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_128(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_130(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_129(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_131(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_130(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_132(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_131(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_133(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_132(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_134(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_133(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_135(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_134(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_136(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_135(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_137(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_136(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_138(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_137(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_139(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_138(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_140(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_139(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_141(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_140(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_142(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_141(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_143(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_142(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_144(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_143(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_145(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_144(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_146(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_145(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_147(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_146(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_148(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_147(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_149(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_148(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_150(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_149(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_151(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_150(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_152(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_151(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_153(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_152(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_154(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_153(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_155(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_154(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_156(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_155(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_157(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_156(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_158(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_157(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_159(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_158(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_160(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_159(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_161(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_160(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_162(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_161(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_163(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_162(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_164(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_163(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_165(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_164(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_166(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_165(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_167(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_166(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_168(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_167(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_169(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_168(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_170(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_169(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_171(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_170(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_172(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_171(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_173(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_172(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_174(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_173(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_175(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_174(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_176(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_175(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_177(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_176(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_178(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_177(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_179(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_178(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_180(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_179(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_181(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_180(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_182(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_181(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_183(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_182(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_184(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_183(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_185(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_184(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_186(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_185(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_187(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_186(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_188(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_187(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_189(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_188(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_190(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_189(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_191(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_190(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_192(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_191(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_193(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_192(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_194(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_193(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_195(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_194(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_196(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_195(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_197(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_196(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_198(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_197(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_199(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_198(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_200(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_199(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_201(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_200(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_202(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_201(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_203(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_202(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_204(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_203(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_205(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_204(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_206(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_205(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_207(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_206(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_208(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_207(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_209(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_208(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_210(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_209(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_211(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_210(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_212(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_211(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_213(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_212(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_214(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_213(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_215(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_214(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_216(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_215(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_217(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_216(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_218(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_217(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_219(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_218(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_220(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_219(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_221(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_220(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_222(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_221(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_223(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_222(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_224(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_223(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_225(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_224(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_226(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_225(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_227(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_226(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_228(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_227(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_229(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_228(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_230(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_229(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_231(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_230(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_232(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_231(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_233(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_232(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_234(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_233(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_235(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_234(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_236(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_235(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_237(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_236(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_238(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_237(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_239(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_238(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_240(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_239(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_241(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_240(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_242(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_241(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_243(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_242(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_244(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_243(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_245(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_244(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_246(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_245(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_247(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_246(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_248(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_247(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_249(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_248(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_250(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_249(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_251(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_250(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_252(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_251(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_253(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_252(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_254(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_253(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_255(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_254(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_256(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_255(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_257(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_256(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_258(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_257(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_259(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_258(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_260(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_259(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_261(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_260(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_262(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_261(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_263(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_262(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_264(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_263(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_265(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_264(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_266(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_265(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_267(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_266(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_268(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_267(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_269(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_268(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_270(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_269(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_271(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_270(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_272(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_271(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_273(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_272(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_274(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_273(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_275(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_274(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_276(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_275(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_277(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_276(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_278(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_277(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_279(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_278(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_280(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_279(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_281(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_280(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_282(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_281(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_283(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_282(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_284(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_283(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_285(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_284(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_286(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_285(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_287(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_286(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_288(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_287(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_289(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_288(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_290(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_289(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_291(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_290(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_292(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_291(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_293(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_292(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_294(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_293(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_295(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_294(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_296(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_295(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_297(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_296(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_298(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_297(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_299(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_298(m, data, s+1, __VA_ARGS__))

#define PP_ENUM_SEQ_I_1(m,  data, s, x)      m(data, 0, s, x)
#define PP_ENUM_SEQ_I_2(m,  data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_1 (m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_3(m,  data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_2 (m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_4(m,  data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_3 (m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_5(m,  data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_4 (m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_6(m,  data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_5 (m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_7(m,  data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_6 (m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_8(m,  data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_7 (m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_9(m,  data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_8 (m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_10(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_9 (m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_11(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_10(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_12(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_11(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_13(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_12(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_14(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_13(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_15(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_14(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_16(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_15(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_17(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_16(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_18(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_17(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_19(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_18(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_20(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_19(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_21(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_20(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_22(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_21(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_23(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_22(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_24(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_23(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_25(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_24(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_26(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_25(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_27(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_26(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_28(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_27(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_29(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_28(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_30(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_29(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_31(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_30(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_32(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_31(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_33(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_32(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_34(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_33(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_35(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_34(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_36(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_35(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_37(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_36(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_38(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_37(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_39(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_38(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_40(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_39(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_41(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_40(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_42(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_41(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_43(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_42(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_44(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_43(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_45(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_44(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_46(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_45(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_47(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_46(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_48(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_47(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_49(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_48(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_50(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_49(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_51(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_50(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_52(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_51(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_53(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_52(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_54(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_53(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_55(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_54(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_56(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_55(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_57(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_56(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_58(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_57(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_59(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_58(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_60(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_59(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_61(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_60(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_62(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_61(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_63(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_62(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_64(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_63(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_65(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_64(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_66(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_65(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_67(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_66(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_68(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_67(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_69(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_68(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_70(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_69(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_71(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_70(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_72(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_71(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_73(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_72(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_74(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_73(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_75(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_74(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_76(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_75(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_77(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_76(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_78(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_77(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_79(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_78(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_80(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_79(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_81(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_80(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_82(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_81(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_83(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_82(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_84(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_83(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_85(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_84(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_86(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_85(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_87(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_86(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_88(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_87(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_89(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_88(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_90(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_89(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_91(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_90(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_92(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_91(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_93(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_92(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_94(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_93(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_95(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_94(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_96(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_95(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_97(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_96(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_98(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_97(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_99(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_98(m, data, s+1, __VA_ARGS__))
#define PP_ENUM_SEQ_I_100(m, data, s, x, ...) m(data, PP_VARADICAL_ENUM_COUNT(__VA_ARGS__), s, x) IDENTITY(PP_ENUM_SEQ_I_99(m, data, s+1, __VA_ARGS__))
#endif